### ISSUE TITLE
@next milestone

### ISSUE THREAD

**Issue by Cody2333** [Cody2333/koa-swagger-decorator#91]
- [ ]  remove all babel / js files
- [ ]  expose more decorators for convenience
- [ ]  seperating router related decorators & pure swagger related decorators
- [ ] 90%+ test coverage 

- [ ] using OpenAPI v3
- [ ] generating d.ts definitions for swagger definitions

**Comment by wong2** [comment]
Any progress?
